

const messageTypes = {
	PATIENT_FOUND:"PATIENT_FOUND",
	PATIENT_NOT_FOUND:"PATIENT_NOT_FOUND",

	HEALTH_WORKER_FOUND:"HEALTH_WORKER_FOUND",
	HEALTH_WORKER_NOT_FOUND:"HEALTH_WORKER_NOT_FOUND",

	PATIENT_REJECT_LIVE_REQUEST_MATCHING: "PATIENT_REJECT_LIVE_REQUEST_MATCHING",
	PATIENT_APPROVE_LIVE_REQUEST_MATCHING: "PATIENT_APPROVE_LIVE_REQUEST_MATCHING",

	HEALTH_WORKER_REJECT_LIVE_REQUEST_MATCHING: "HEALTH_WORKER_REJECT_LIVE_REQUEST_MATCHING",
	HEALTH_WORKER_APPROVE_LIVE_REQUEST_MATCHING: "HEALTH_WORKER_APPROVE_LIVE_REQUEST_MATCHING",


	PATIENT_REJECT_APPOINTMENT_MATCHING: "PATIENT_REJECT_APPOINTMENT_MATCHING",
	PATIENT_APPROVE_APPOINTMENT_MATCHING: "PATIENT_APPROVE_APPOINTMENT_MATCHING",

	HEALTH_WORKER_REJECT_APPOINTMENT_MATCHING: "HEALTH_WORKER_REJECT_APPOINTMENT_MATCHING",
	HEALTH_WORKER_APPROVE_APPOINTMENT_MATCHING: "HEALTH_WORKER_APPROVE_APPOINTMENT_MATCHING",

	HEALTH_WORKER_ARRIVAL:"HEALTH_WORKER_ARRIVAL",
	PATIENT_ERROR:"PATIENT_ERROR",
	POTENTIAL_HEALTH_WORKERS_MESSAGE:"POTENTIAL_HEALTH_WORKERS_MESSAGE",


	HEALTH_WORKER_APPOINTMENT_NOT_FOUND:"HEALTH_WORKER_APPOINTMENT_NOT_FOUND",
	PATIENT_REQUEST_APPOINTMENT:"PATIENT_REQUEST_APPOINTMENT"

}

export default messageTypes
