


const Screens = {
     LOGIN_SCREEN:"LOGIN_SCREEN",
     SIGN_UP_SCREEN:"SIGN_UP_SCREEN",
     DASHBOARD_SCREEN:"DASHBOARD_SCREEN",

     HOME_SCREEN:"HOME_SCREEN",
     SCHEDULE_SCREEN:"SCHEDULE_SCREEN",
     DATA_VIEW_SCREEN:"DATA_VIEW_SCREEN",
     SELECT_CATEGORY_SCREEN:"SELECT_CATEGORY_SCREEN",
     REQUESTING_SCREEN:"REQUESTING_SCREEN",
     ACCEPTED_SCREEN:"ACCEPTED_SCREEN",
     MY_DATA_SCREEN:"MY_DATA_SCREEN",
     MY_REQUESTS_SCREEN:"MY_REQUESTS_SCREEN",
     MY_PAYMENTS_SCREEN:"MY_PAYMENTS_SCREEN",
     SUPPORT_SCREEN:"Support Centre",
     SHARE_SCREEN:"Share ",
     PAYMENT_SCREEN:"PAYMENT_SCREEN",
     RATING_AND_REVIEWS_SCREEN:"RATING_AND_REVIEWS_SCREEN",
     ACCOUNT_SCREEN:"ACCOUNT_SCREEN",
     SINGLE_VISIT_SCREEN:"SINGLE_VISIT_SCREEN",


     SELECT_DATE_AND_TIME_SCREEN:"SELECT_DATE_AND_TIME_SCREEN",
     SELECT_SCHEDULING_CATEGORY_SCREEN:"SELECT_SCHEDULING_CATEGORY_SCREEN",
     REQUEST_SCHEDULE_SCREEN:"REQUEST_SCHEDULE_SCREEN",
     ACCEPTED_APPOINTMENT_SCREEN:"ACCEPTED_APPOINTMENT_SCREEN",
     SELECT_LOCATION_APPOINTMENT_SCREEN:"SELECT_LOCATION_APPOINTMENT_SCREEN"



}

export default Screens;
