

const webSocketConstants = {
	SEARCHING_PATIENTS:"SEARCHING_PATIENTS",
	SEARCHING_HEALTH_CARE_WORKERS:"SEARCHING_HEALTH_CARE_WORKERS",

	CANCEL_SEARCHING_PATIENTS:"CANCEL_SEARCHING_PATIENTS",
	CANCEL_SEARCHING_HEALTH_CARE_WORKERS:"CANCEL_SEARCHING_HEALTH_CARE_WORKERS",

	REJECT_PATIENT:"REJECT_PATIENT",
	REJECT_HEALTH_CARE_WORKER:"REJECT_HEALTH_CARE_WORKER",

	REQUEST_LIVE_REQUEST:"REQUEST_LIVE_REQUEST",
	REQUEST_APPOINTMENT_REQUEST:"REQUEST_APPOINTMENT_REQUEST",

	APPROVE_LIVE_REQUEST:"APPROVE_LIVE_REQUEST",
	APPROVE_APPOINTMENT_REQUEST:"APPROVE_APPOINTMENT_REQUEST",

	FOUND_PATIENT: "FOUND_PATIENT",
	FOUND_PROFESSIONAL: "FOUND_PROFESSIONAL",

	NOT_FOUND_PATIENT:"NOT_FOUND_PATIENT",
	NOT_FOUND_PROFESSIONAL:"NOT_FOUND_PROFESSIONAL",

	PATIENT_CANCEL_MATCHING:"PATIENT_CANCEL_MATCHING",
	HEALTH_WORKER_CANCEL_MATCHING:"HEALTH_WORKER_CANCEL_MATCHING",
	UPDATE_USER_LOCATION:"UPDATE_USER_LOCATION",
	LOCATION_UPDATED:"LOCATION_UPDATED"



}

export default webSocketConstants
