
export const Actions = {
     LOGIN_USER: 'LOGIN_USER',
     LOGOUT_USER: 'LOGOUT_USER',

     SET_LOCATION:"SET_LOCATION",
     SET_ADDRESS:"SET_ADDRESS",
     SET_CUSTOM_LOCATION:"SET_CUSTOM_LOCATION",

     NEXT_STEP:"NEXT_STEP",
     PREVIOUS_STEP:"PREVIOUS_STEP",
     GO_TO_STEP:"GO_TO_STEP",

     SET_MATCHED_HEALTH_CARE_WORKER:"SET_MATCHED_HEALTH_CARE_WORKER",
     UN_SET_HEALTH_CARE_WORKER:"UN_SET_HEALTH_CARE_WORKER",

     SET_MATCHED_HEALTH_CARE_WORKER_DISTANCE_INFO:"SET_MATCHED_HEALTH_CARE_WORKER_DISTANCE_INFO",
     UN_SET_MATCHED_HEALTH_CARE_WORKER_DISTANCE_INFO:"UN_SET_MATCHED_HEALTH_CARE_WORKER_DISTANCE_INFO",




}
